# Generated by Django 6.0.5 on 2026-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50, null=True)),
                ('Institution', models.CharField(max_length=50, null=True)),
                ('GraduationYear', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePicture', models.ImageField(null=True, upload_to='static/picture')),
                ('FullName', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('CareerObjective', models.TextField(null=True)),
                ('Skills', models.CharField(max_length=50, null=True)),
                ('Certification', models.CharField(max_length=50, null=True)),
                ('Projects', models.CharField(max_length=50, null=True)),
                ('References', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50, null=True)),
                ('Position', models.CharField(max_length=50, null=True)),
                ('StartDate', models.CharField(max_length=50, null=True)),
                ('EndDate', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
